C:\Users\me\.jdks\temurin-17.0.10\bin\java.exe -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.4\lib\idea_rt.jar=56231:C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.4\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.4\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.4\plugins\testng\lib\testng-rt.jar;C:\workspaces\test\EasyMockErrorShowCase\target\test-classes;C:\workspaces\test\EasyMockErrorShowCase\target\classes;C:\Users\me\.m2\repository\org\testng\testng\7.10.1\testng-7.10.1.jar;C:\Users\me\.m2\repository\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;C:\Users\me\.m2\repository\com\beust\jcommander\1.82\jcommander-1.82.jar;C:\Users\me\.m2\repository\org\webjars\jquery\3.7.1\jquery-3.7.1.jar;C:\Users\me\.m2\repository\org\easymock\easymock\5.2.0\easymock-5.2.0.jar;C:\Users\me\.m2\repository\org\objenesis\objenesis\3.3\objenesis-3.3.jar" com.intellij.rt.testng.RemoteTestNGStarter -usedefaultlisteners false -socket56230 @w@C:\Users\me\AppData\Local\Temp\idea_working_dirs_testng.tmp -temp C:\Users\me\AppData\Local\Temp\idea_testng.tmp
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

java.lang.RuntimeException: java.lang.IllegalAccessException: no such field: com.sun.net.httpserver.HttpExchange$$$EasyMock$1.$callback/org.easymock.internal.ClassMockingData/putField

	at org.easymock.internal.ClassProxyFactory.getCallbackSetter(ClassProxyFactory.java:282)
	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:213)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:110)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:83)
	at org.easymock.IMocksControl.mock(IMocksControl.java:44)
	at org.easymock.EasyMock.mock(EasyMock.java:70)
	at ShowCaseTest.nothing(ShowCaseTest.java:8)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
	at org.testng.SuiteRunner.run(SuiteRunner.java:312)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
	at org.testng.TestNG.runSuites(TestNG.java:1112)
	at org.testng.TestNG.run(TestNG.java:1079)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.lang.IllegalAccessException: no such field: com.sun.net.httpserver.HttpExchange$$$EasyMock$1.$callback/org.easymock.internal.ClassMockingData/putField
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:972)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3641)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findSetter(MethodHandles.java:3043)
	at org.easymock.internal.ClassProxyFactory.getCallbackSetter(ClassProxyFactory.java:280)
	... 33 more
Caused by: java.lang.LinkageError: bad field type alias: class org.easymock.internal.ClassMockingData not visible from class com.sun.net.httpserver.HttpExchange$$$EasyMock$1
	at java.base/java.lang.invoke.MemberName.checkForTypeAlias(MemberName.java:886)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1089)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
	... 36 more


===============================================
Default Suite
Total tests run: 1, Passes: 0, Failures: 1, Skips: 0
===============================================


Process finished with exit code 0
